allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@biomejs/biome@2.4.16'
  - '@biomejs/cli-darwin-arm64@2.4.16'
  - '@biomejs/cli-darwin-x64@2.4.16'
  - '@biomejs/cli-linux-arm64-musl@2.4.16'
  - '@biomejs/cli-linux-arm64@2.4.16'
  - '@biomejs/cli-linux-x64-musl@2.4.16'
  - '@biomejs/cli-linux-x64@2.4.16'
  - '@biomejs/cli-win32-arm64@2.4.16'
  - '@biomejs/cli-win32-x64@2.4.16'
  - '@inertiajs/core@3.3.0'
  - '@inertiajs/react@3.3.0'
  - '@inertiajs/vite@3.3.0'
  - '@oxc-project/types@0.132.0'
  - '@rolldown/binding-android-arm64@1.0.2'
  - '@rolldown/binding-darwin-arm64@1.0.2'
  - '@rolldown/binding-darwin-x64@1.0.2'
  - '@rolldown/binding-freebsd-x64@1.0.2'
  - '@rolldown/binding-linux-arm-gnueabihf@1.0.2'
  - '@rolldown/binding-linux-arm64-gnu@1.0.2'
  - '@rolldown/binding-linux-arm64-musl@1.0.2'
  - '@rolldown/binding-linux-ppc64-gnu@1.0.2'
  - '@rolldown/binding-linux-s390x-gnu@1.0.2'
  - '@rolldown/binding-linux-x64-gnu@1.0.2'
  - '@rolldown/binding-linux-x64-musl@1.0.2'
  - '@rolldown/binding-openharmony-arm64@1.0.2'
  - '@rolldown/binding-wasm32-wasi@1.0.2'
  - '@rolldown/binding-win32-arm64-msvc@1.0.2'
  - '@rolldown/binding-win32-x64-msvc@1.0.2'
  - '@types/node@25.9.0'
  - concurrently@10.0.0
  - lucide-react@1.17.0
  - postcss@8.5.15
  - rolldown@1.0.2
  - shell-quote@1.8.4
  - vite@8.0.14
